# This is a basic workflow to help you get started with Actions

name: CI

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

# Controls when the workflow will run
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        
      # 获取PR信息并将其添加到环境变量
      - name: set PR_INFO 
      - run: echo PR_TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH") >> $GITHUB_ENV

      # 打印环境变量
      - name: print env
      - run: printenv
